<template>
  <v-progress-linear
    v-if="loadingACBFiles"
    indeterminate
    color="teal"
    class="mb-2"
  />
  <empty-state
    v-if="!loadingACBFiles && acbFiles.length === 0"
    icon="mdi-file-document-outline"
    title="No ACB files generated yet"
    message="Generate an ACB file to start a BankServ payment run."
  />
  <v-list v-else density="compact" class="border rounded">
    <v-list-item
      v-for="acb in acbFiles"
      :key="acb.id"
      :subtitle="`Generated by ${acb.generated_by} on ${formatDate(acb.generated_at)} | ${acb.transaction_count} transactions | ${formatCurrency(acb.total_amount)}`"
      :title="acb.file_name"
    >
      <template #prepend>
        <v-icon :color="acb.status === 'reconciled' ? 'success' : 'teal'">
          {{
            acb.status === 'reconciled'
              ? 'mdi-check-circle'
              : 'mdi-file-document'
          }}
        </v-icon>
      </template>
      <template #append>
        <div class="d-flex gap-1 align-center">
          <v-chip
            v-if="acb.is_retry"
            size="x-small"
            color="orange"
            variant="tonal"
            class="mr-1"
          >
            Retry
          </v-chip>
          <v-chip
            :color="acb.status === 'reconciled' ? 'success' : 'grey'"
            size="x-small"
            label
          >
            {{ acb.status }}
          </v-chip>
          <v-btn
            size="x-small"
            variant="text"
            color="primary"
            icon="mdi-download"
            :loading="downloadingACB === acb.id"
            @click="downloadACBFile(acb)"
          />
        </div>
      </template>
    </v-list-item>
  </v-list>
</template>

<script setup lang="ts">
import { inject, onMounted } from 'vue'
import EmptyState from '@/renderer/components/EmptyState.vue'
import { PAYMENT_SCHEDULE_CONTEXT } from './payment_schedule_context'

const ctx = inject(PAYMENT_SCHEDULE_CONTEXT)
if (!ctx) {
  throw new Error(
    'ClaimPaymentScheduleACB must be rendered inside ClaimPaymentScheduleLayout'
  )
}

const {
  acbFiles,
  loadingACBFiles,
  downloadingACB,
  loadACBFiles,
  downloadACBFile,
  formatCurrency,
  formatDate,
  schedule
} = ctx

onMounted(async () => {
  if (schedule.value && acbFiles.value.length === 0) {
    await loadACBFiles()
  }
})
</script>
